"""提供 Robotics-AR 静态状态集合和转移检查。

Provide the Robotics-AR static state set and transition validation.
"""

from __future__ import annotations

from typing import FrozenSet, Mapping, Set


STATES = (
    "UNINITIALIZED",
    "BOOTSTRAP_VALIDATING",
    "PLANNING_READY",
    "BLOCKED_DEPENDENCY",
    "BLOCKED_ENVIRONMENT",
    "INVOKING_IDEA_SKILL",
    "AWAITING_IDEA_APPROVAL",
    "INVOKING_EXPERIMENT_SKILL",
    "AWAITING_EXPERIMENT_APPROVAL",
    "TASK_COMPILATION",
    "AWAITING_TASK_APPROVAL",
    "IMPLEMENTING",
    "TESTING",
    "DEBUGGING",
    "EXECUTION_READY",
    "RUNNING_ENVIRONMENT",
    "ANALYZING",
    "AWAITING_BATCH_REVIEW",
    "EVIDENCE_FREEZE",
    "AWAITING_EVIDENCE_APPROVAL",
    "INVOKING_WRITING_SKILL",
    "AWAITING_WRITING_APPROVAL",
    "INVOKING_REVIEW_SKILL",
    "AWAITING_REVIEW_ROUTE",
    "PAUSING",
    "PAUSED",
    "FAILED_RECOVERABLE",
    "ABORTED",
    "COMPLETE",
)

_T = {
    "UNINITIALIZED": {"BOOTSTRAP_VALIDATING"},
    "BOOTSTRAP_VALIDATING": {"PLANNING_READY", "BLOCKED_DEPENDENCY", "BLOCKED_ENVIRONMENT", "FAILED_RECOVERABLE", "INVOKING_IDEA_SKILL", "AWAITING_IDEA_APPROVAL", "INVOKING_EXPERIMENT_SKILL", "AWAITING_EXPERIMENT_APPROVAL", "INVOKING_WRITING_SKILL", "AWAITING_WRITING_APPROVAL", "INVOKING_REVIEW_SKILL", "AWAITING_REVIEW_ROUTE", "TASK_COMPILATION", "AWAITING_TASK_APPROVAL", "IMPLEMENTING", "TESTING", "DEBUGGING", "EXECUTION_READY", "RUNNING_ENVIRONMENT", "ANALYZING", "AWAITING_BATCH_REVIEW", "EVIDENCE_FREEZE", "AWAITING_EVIDENCE_APPROVAL", "PAUSING"},
    "PLANNING_READY": {"INVOKING_IDEA_SKILL", "INVOKING_EXPERIMENT_SKILL", "INVOKING_WRITING_SKILL", "INVOKING_REVIEW_SKILL", "TASK_COMPILATION", "PAUSING", "COMPLETE"},
    "BLOCKED_DEPENDENCY": {"PLANNING_READY", "PAUSING", "ABORTED"},
    "BLOCKED_ENVIRONMENT": {"PLANNING_READY", "EXECUTION_READY", "PAUSING", "ABORTED"},
    "INVOKING_IDEA_SKILL": {"AWAITING_IDEA_APPROVAL", "BLOCKED_DEPENDENCY", "FAILED_RECOVERABLE", "PAUSING"},
    "AWAITING_IDEA_APPROVAL": {"INVOKING_EXPERIMENT_SKILL", "TASK_COMPILATION", "PAUSING", "ABORTED"},
    "INVOKING_EXPERIMENT_SKILL": {"AWAITING_EXPERIMENT_APPROVAL", "BLOCKED_DEPENDENCY", "FAILED_RECOVERABLE", "PAUSING"},
    "AWAITING_EXPERIMENT_APPROVAL": {"TASK_COMPILATION", "PAUSING", "ABORTED"},
    "TASK_COMPILATION": {"AWAITING_TASK_APPROVAL", "FAILED_RECOVERABLE", "PAUSING"},
    "AWAITING_TASK_APPROVAL": {"IMPLEMENTING", "PAUSING", "ABORTED"},
    "IMPLEMENTING": {"TESTING", "DEBUGGING", "FAILED_RECOVERABLE", "PAUSING"},
    "TESTING": {"EXECUTION_READY", "DEBUGGING", "FAILED_RECOVERABLE", "PAUSING"},
    "DEBUGGING": {"IMPLEMENTING", "TESTING", "FAILED_RECOVERABLE", "PAUSING"},
    "EXECUTION_READY": {"RUNNING_ENVIRONMENT", "BLOCKED_ENVIRONMENT", "PAUSING", "ABORTED"},
    "RUNNING_ENVIRONMENT": {"ANALYZING", "BLOCKED_ENVIRONMENT", "PAUSING", "FAILED_RECOVERABLE", "ABORTED"},
    "ANALYZING": {"AWAITING_BATCH_REVIEW", "EVIDENCE_FREEZE", "FAILED_RECOVERABLE", "PAUSING"},
    "AWAITING_BATCH_REVIEW": {"EVIDENCE_FREEZE", "DEBUGGING", "PAUSING", "ABORTED"},
    "EVIDENCE_FREEZE": {"AWAITING_EVIDENCE_APPROVAL", "INVOKING_WRITING_SKILL", "INVOKING_REVIEW_SKILL", "PAUSING"},
    "AWAITING_EVIDENCE_APPROVAL": {"INVOKING_WRITING_SKILL", "INVOKING_REVIEW_SKILL", "PAUSING", "ABORTED"},
    "INVOKING_WRITING_SKILL": {"AWAITING_WRITING_APPROVAL", "BLOCKED_DEPENDENCY", "FAILED_RECOVERABLE", "PAUSING"},
    "AWAITING_WRITING_APPROVAL": {"INVOKING_REVIEW_SKILL", "PAUSING", "ABORTED"},
    "INVOKING_REVIEW_SKILL": {"AWAITING_REVIEW_ROUTE", "BLOCKED_DEPENDENCY", "FAILED_RECOVERABLE", "PAUSING"},
    "AWAITING_REVIEW_ROUTE": {"INVOKING_IDEA_SKILL", "INVOKING_EXPERIMENT_SKILL", "INVOKING_WRITING_SKILL", "COMPLETE", "PAUSING", "ABORTED"},
    "PAUSING": {"PAUSED", "FAILED_RECOVERABLE"},
    "PAUSED": {"BOOTSTRAP_VALIDATING", "ABORTED"},
    "FAILED_RECOVERABLE": {"BOOTSTRAP_VALIDATING", "PAUSING", "ABORTED"},
    "ABORTED": set(),
    "COMPLETE": set(),
}

ALLOWED_TRANSITIONS: Mapping[str, FrozenSet[str]] = {key: frozenset(value) for key, value in _T.items()}
ACTIVE_STATES: FrozenSet[str] = frozenset(set(STATES) - {"UNINITIALIZED", "PAUSED", "ABORTED", "COMPLETE"})


class TransitionError(ValueError):
    """未知或未允许的状态转移。 / Raised for unknown or disallowed transitions."""


def validate_transition(previous: str, new: str) -> None:
    """验证静态 transition table。 / Validate the static transition table."""

    if previous not in ALLOWED_TRANSITIONS:
        raise TransitionError(f"unknown previous state: {previous}")
    if new not in ALLOWED_TRANSITIONS:
        raise TransitionError(f"unknown new state: {new}")
    if new not in ALLOWED_TRANSITIONS[previous]:
        raise TransitionError(f"transition not allowed: {previous} -> {new}")


def is_active_state(state: str) -> bool:
    """判断状态是否可暂停。 / Return whether a state is pausable."""

    return state in ACTIVE_STATES
